services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secrets
      POSTGRES_DB: scrumlord
    volumes:
      - data:/var/lib/postgresql/data
      - ./api/db-ddl.sql:/docker-entrypoint-initdb.d/init.sql
  # todo: connection between API and DB refused
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile-API
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgresql://user:secrets@localhost:5432/scrumlord
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - postgres

volumes:
  data: